
java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Control:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Output Myc_Myc > Myc_Myc.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Control:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Output Myc_Oidia > Myc_Oidia.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Control:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Output Myc_Scl > Myc_Scl.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Control:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Output Myc_Knot > Myc_Knot.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Control:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Output Myc_Pri > Myc_Pri.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Control:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Output Myc_YFB > Myc_YFB.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Control:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Output Myc_BS > Myc_BS.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Control:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Output Myc_BS12h > Myc_BS12h.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Control:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Output Myc_BS24h > Myc_BS24h.log &

wait


java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Control:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Output Oidia_Myc > Oidia_Myc.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Control:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Output Oidia_Oidia > Oidia_Oidia.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Control:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Output Oidia_Scl > Oidia_Scl.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Control:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Output Oidia_Knot > Oidia_Knot.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Control:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Output Oidia_Pri > Oidia_Pri.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Control:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Output Oidia_YFB > Oidia_YFB.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Control:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Output Oidia_BS > Oidia_BS.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Control:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Output Oidia_BS12h > Oidia_BS12h.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Control:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Output Oidia_BS24h > Oidia_BS24h.log &

wait


java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Control:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Output Scl_Myc > Scl_Myc.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Control:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Output Scl_Oidia > Scl_Oidia.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Control:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Output Scl_Scl > Scl_Scl.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Control:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Output Scl_Knot > Scl_Knot.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Control:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Output Scl_Pri > Scl_Pri.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Control:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Output Scl_YFB > Scl_YFB.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Control:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Output Scl_BS > Scl_BS.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Control:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Output Scl_BS12h > Scl_BS12h.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Control:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Output Scl_BS24h > Scl_BS24h.log &

wait


java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Control:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Output Knot_Myc > Knot_Myc.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Control:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Output Knot_Oidia > Knot_Oidia.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Control:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Output Knot_Scl > Knot_Scl.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Control:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Output Knot_Knot > Knot_Knot.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Control:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Output Knot_Pri > Knot_Pri.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Control:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Output Knot_YFB > Knot_YFB.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Control:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Output Knot_BS > Knot_BS.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Control:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Output Knot_BS12h > Knot_BS12h.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Control:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Output Knot_BS24h > Knot_BS24h.log &

wait


java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Control:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Output Pri_Myc > Pri_Myc.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Control:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Output Pri_Oidia > Pri_Oidia.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Control:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Output Pri_Scl > Pri_Scl.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Control:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Output Pri_Knot > Pri_Knot.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Control:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Output Pri_Pri > Pri_Pri.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Control:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Output Pri_YFB > Pri_YFB.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Control:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Output Pri_BS > Pri_BS.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Control:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Output Pri_BS12h > Pri_BS12h.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Control:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Output Pri_BS24h > Pri_BS24h.log &

wait


java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Control:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Output YFB_Myc > YFB_Myc.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Control:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Output YFB_Oidia > YFB_Oidia.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Control:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Output YFB_Scl > YFB_Scl.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Control:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Output YFB_Knot > YFB_Knot.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Control:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Output YFB_Pri > YFB_Pri.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Control:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Output YFB_YFB > YFB_YFB.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Control:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Output YFB_BS > YFB_BS.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Control:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Output YFB_BS12h > YFB_BS12h.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Control:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Output YFB_BS24h > YFB_BS24h.log &

wait


java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Control:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Output BS_Myc > BS_Myc.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Control:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Output BS_Oidia > BS_Oidia.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Control:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Output BS_Scl > BS_Scl.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Control:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Output BS_Knot > BS_Knot.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Control:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Output BS_Pri > BS_Pri.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Control:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Output BS_YFB > BS_YFB.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Control:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Output BS_BS > BS_BS.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Control:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Output BS_BS12h > BS_BS12h.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Control:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Output BS_BS24h > BS_BS24h.log &

wait


java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Control:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Output BS12h_Myc > BS12h_Myc.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Control:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Output BS12h_Oidia > BS12h_Oidia.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Control:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Output BS12h_Scl > BS12h_Scl.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Control:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Output BS12h_Knot > BS12h_Knot.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Control:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Output BS12h_Pri > BS12h_Pri.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Control:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Output BS12h_YFB > BS12h_YFB.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Control:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Output BS12h_BS > BS12h_BS.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Control:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Output BS12h_BS12h > BS12h_BS12h.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Control:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Output BS12h_BS24h > BS12h_BS24h.log &

wait


java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Myc /home/yichun/RNAmodification/redubam/M1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/M3.sorted.redu.bam --Control:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Output BS24h_Myc > BS24h_Myc.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Oidia /home/yichun/RNAmodification/redubam/O1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/O3.sorted.redu.bam --Control:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Output BS24h_Oidia > BS24h_Oidia.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Scl /home/yichun/RNAmodification/redubam/S1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/S3.sorted.redu.bam --Control:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Output BS24h_Scl > BS24h_Scl.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Knot /home/yichun/RNAmodification/redubam/K1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/K3.sorted.redu.bam --Control:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Output BS24h_Knot > BS24h_Knot.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:Pri /home/yichun/RNAmodification/redubam/P1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/P3.sorted.redu.bam --Control:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Output BS24h_Pri > BS24h_Pri.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:YFB /home/yichun/RNAmodification/redubam/YFB1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/YFB3.sorted.redu.bam --Control:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Output BS24h_YFB > BS24h_YFB.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS /home/yichun/RNAmodification/redubam/BS1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS3.sorted.redu.bam --Control:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Output BS24h_BS > BS24h_BS.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS12h /home/yichun/RNAmodification/redubam/BS12h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS12h3.sorted.redu.bam --Control:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Output BS24h_BS12h > BS24h_BS12h.log &

java -jar -Xmx50g /home/yichun/tools/cash_v2.2.1/cash.jar --MergePval G --Combine True --DisplayAllEvent True --StrandSpecific NONE --SpliceCons True --JuncAllSample 25 --JuncOneGroup 10 --minAnchorLen 5 --minIntronLen 25 --minJuncReadsForNewIso 10 --runSepChr True --GTF /home/yichun/RNAmodification/genome/Coprinopsis_cinerea_A43mutB43mut_pab1-1_326.gff3 --Case:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Control:BS24h /home/yichun/RNAmodification/redubam/BS24h1.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h2.sorted.redu.bam,/home/yichun/RNAmodification/redubam/BS24h3.sorted.redu.bam --Output BS24h_BS24h > BS24h_BS24h.log &

wait

